services:
  llamacpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    ipc: host
    ports:
      - 15932:8080
    volumes:
      - ./llama.cpp:/root/.cache/llama.cpp
    command:
      - -m
      - "/root/.cache/llama.cpp/Qwen2.5-1.5B-Instruct/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --reasoning-format
      - none
      - --alias
      - "Qwen2.5-1.5B-Instruct"
      - --ctx-size
      - "65535"
      - --parallel
      - "1"
      - --threads
      - "8"
      - --flash-attn
      - on
      - --batch-size
      - "256"
      - --ubatch-size
      - "256"
      - --temp
      - "0.6"
      - --top-p
      - "0.95"
      - --top-k
      - "20"
      - --min-p
      - "0.0"
      - --presence-penalty
      - "0.0"
      - --repeat-penalty
      - "1.0"

  llm-api:
    image: ghcr.io/opl24865/llama-test:b9f3e7b
    container_name: llm-api
    depends_on:
      - llamacpp-server
    ports:
      - "8000:8000"
    environment:
      - LLM_BASE_URL=http://llamacpp-server:8080/v1
      - LLM_MODEL=Qwen2.5-1.5B-Instruct
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 


#  my-python-app:
#    build: .                          # ← 用當前目錄的 Dockerfile build
#    depends_on:
#      - llamacpp-server    